Level 2
losbojos/movies-explorer-frontend pull request #2
Opened 2023-08-31 17:47 UTC by losbojos

Вся верстка с исправлениями

2023-09-01 10:01 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- Страница с Фильмами - Нет карточек с фильмами https://yadi.sk/d/H7g4MWVrcTo_fw
- Главная 320 https://yadi.sk/d/HEHqx9r56IwOpw
- Регистрация/Взод 320 https://yadi.sk/d/4na2CmLAxJ186w
- Меню 768 https://yadi.sk/d/Q6m0hQzfL6ucvw нет главной
- Сохраненные 1280 https://yadi.sk/d/juvYNL7mbK8M8g отступ до подвала
- Профиль 768 https://yadi.sk/d/yRin9a5eM9chOQ
- 404 1280 https://yadi.sk/d/lsaZSE8QKmCSEQ

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

- https://yadi.sk/i/soYywWEZzW6lRA небольшие ошибки по БЭМ.
- customcheckbox, moviescardlist__listitem, navigation__list-item, aboutme и т.д. - при именовании классов придерживайтесь единообразия, так в большинстве случаев используется кебаб-кейс (custom-checkbox), на примере скорректируйте остальные подобные случаи.
- about-project__header_h3 - именование не привязывайте к селекторам слишком жестко, бывает, что заголовок оформлен другим семантическим селектором (h2, p и т.д.). Здесь хорошо подойдут сложные модификаторы about-project__header_font_small. В текущей разметке ему смело можно дать отдельный класс, about-project__title, например.

- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- navigation__listitem - стрелочка - хорошо декоративные элементы расположить на псевдоэлементе, чтобы упростить разметку и семантику
- promo__banner - баннер носит декоративный характер, его можно разместить фоновым изображением или на псевдоэлементе.
- aboutme__line, about-project__line, footer__line и т.д. - декоративные элементы хорошо описывать при помощи стилей не добавляя в разметку, на примере скорректируйте остальные подобные случаи.
- Каждой отдельной странице нужен семантический селектор main (который оборачивает весь главный контент, кроме header и footer), семантические section главным блокам - все страницы, кроме Главной.
- Каждой секции требуется семантический заголовок - Footer, 404
- Каждой странице требуется семантический заголовок 1 уровня - один - 404

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [ ] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.

- https://yadi.sk/d/ZAsbjsURqS73OQ при объявлении семейства шрифта следует указывать альтернативный шрифт, в случае если произойдет ошибка. Можно один раз объявить шрифт корневому документу, чтобы весь проект его унаследовал.

- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 77

## Доп. Комментарии:
- promo.svg - такого рода изображение хорошо сохранить в формате png. Размер будет меньше.
- Фотографии карточек с фильмами имеют размер 2000 по ширине, что больше от размера карточки по макету во много раз (360), хорошо бы их оптимизировать, например, х2-х3 по ширине, это может здорово сократить размер и не повлияет на качество отображения.
- В папке со шрифтами одна толщина не используется по макету
- https://yadi.sk/d/mkm6B-hqPFvs2A Можно оптимизировать компонент и сократить кол-во импортов в jsx файле, если объединить описания селекторов в один файл (как правило названный таким же именем, что и компонент).
- Заголовки секции можно выделить БЭМ блоком, чтобы удалить дублировния, они по стилизации одинаковые

2023-09-01 10:33 UTC, losbojos commented
Здравствуйте! Спасибо за ревью!
Что касается "Страница с Фильмами - Нет карточек с фильмами" - нужно нажать кнопку Поиск и они появятся.

2023-09-01 14:22 UTC, losbojos commented
>> Регистрация/Взод 320 https://yadi.sk/d/4na2CmLAxJ186w
Не смог воспроизвести, у меня четко сходится верстка, браузер Google chrome:
https://disk.yandex.ru/i/FkrrEC2HtTgEeQ

2023-09-02 12:49 UTC, losbojos commented
Верстка 404 1280
Проблема не воспроизвелась, на двух браузерах - Chrome и Firefox все соответсвует дизайну. Судя по скриншоту, подозреваю, что у вас высота окна отличается от макетного, проверьте не только ширину, но и высоту.

2023-09-03 08:33 UTC, losbojos commented
promo__banner - баннер носит декоративный характер, его можно разместить фоновым изображением или на псевдоэлементе.


На мой взгляд оно не может быть фоновым, т.к. занимает свободное место и по дизайну выглядит как блочный элемент, к тому же на разных разрешениях в разных частях секции занимает место.

2023-09-03 08:39 UTC, losbojos commented
>> navigation__listitem - стрелочка - хорошо декоративные элементы расположить на псевдоэлементе, чтобы упростить разметку и семантику
Наверное, имелся в виду другой класс, т.к. в navigation__listitem стрелочек нет. В другом месте исправил (Секция портфолио в лэндинг-пейдж).

2023-09-03 10:48 UTC, losbojos commented
>> Каждой отдельной странице нужен семантический селектор main
А если на странице только form, его тоже в main надо оборачивать? Не нашел информации по этому поводу.

2023-09-03 13:57 UTC, losbojos commented
>> Каждой секции требуется семантический заголовок - Footer, 404
Что это означает? Если я правильно понял, поменял div секций\подсекций на <section>

2023-09-03 13:58 UTC, losbojos commented
> > > Каждой секции требуется семантический заголовок - Footer, 404

Что это означает? Если я правильно понял, то поменял элементы div секций\подсекций на элементы section

2023-09-04 07:37 UTC, closed without merging

2023-09-04 08:35 UTC, Savallera commented
> promo__banner - баннер носит декоративный характер, его можно разместить фоновым изображением или на псевдоэлементе.
> 
> На мой взгляд оно не может быть фоновым, т.к. занимает свободное место и по дизайну выглядит как блочный элемент, к тому же на разных разрешениях в разных частях секции занимает место.

Как вариант Вы можете изображение разместить на псевдоэлементе, и при помощи технологии построения сетки флекс/грид сделать его дочерним элементом. Так его можно будет расположить как блочный.

2023-09-04 08:45 UTC, Savallera commented
> > > Каждой отдельной странице нужен семантический селектор main
> > > А если на странице только form, его тоже в main надо оборачивать? Не нашел информации по этому поводу.

Да, https://doka.guide/html/main/ обратите внимание на данную статью. Main здорово улучшает доступность проекта, т.к. им оборачивают уникальный контент на странице.

2023-09-04 13:44 UTC, losbojos commented
Понятно, благодарю!

2023-09-04 13:45 UTC, losbojos commented
> > promo__banner - баннер носит декоративный характер, его можно разместить фоновым изображением или на псевдоэлементе.
> > На мой взгляд оно не может быть фоновым, т.к. занимает свободное место и по дизайну выглядит как блочный элемент, к тому же на разных разрешениях в разных частях секции занимает место.
> 
> Как вариант Вы можете изображение разместить на псевдоэлементе, и при помощи технологии построения сетки флекс/грид сделать его дочерним элементом. Так его можно будет расположить как блочный.

Ок, попробую позже, спасибо)